### ISSUE TITLE
New player experience

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#354]
This issue is a collection of features that would make the experience for actual new players not coming from similar games much more welcoming and hopefully grow our playerbase longterm by sourcing players not mostly from a dead franchise but adding actual new ones.
I'm collecting under some categories that I consider most important for this experience

## Getting into the game quickly

Getting players to get into the game fast, enabling to configure quickly and without extra effort/complications so that their patience with the game doesn't end before they get excited for it.

- [ ] panel-attack/panel-game#353  While not super complicated, having to configure your gamepad manually can be something confusing; most controller players expect plug&play so even if we don't provide that, we need to put their head right onto the correct menu
- [ ] panel-attack/panel-game#36 is related although for keyboard users and more specific in leading new players through a process
- [x] panel-attack/panel-game#236 should be solved in relation to the two above issues
- [ ] #535 
- [x] panel-attack/panel-game#356 This should ideally precede the creation of a tutorial
- [ ] panel-attack/panel-game#347 Very very very important, there are some technical requirements to make this amazing but even a half-assed tutorial would be a lot better than none

## Giving them something to do

Right now the game is heavily PvP focused. Our community is too powerful and small to provide new players with good training partners and there are effectively no elements that can keep new players engaged until they're good enough to seek out competition. We need to fill the 1p portion of the game with life.

- [ ] panel-attack/panel-game#231 Would allow interaction with the community and online play without getting dumpstered. There are always people with anxiety about competition so this would help rope in those people besides the obvious advantages for coaching new players in discord.
- [ ] panel-attack/panel-game#345 Would allow new players to be able to play against veterans without getting dumpstered. Cause a win with a handicap is still a win, right?
- [ ] panel-attack/panel-game#71 A simple game mode that has a bit more of a goal than endless but is still relaxed. Progress tracking can give the player something to work towards (especially when still struggling to finish the mode).
- [ ] panel-attack/panel-game#234 Any kind of campaign, story that tries to engage the player would be a huge addition to the existing challenge mode. Plucking some strings, filling it with tension.
- [x] panel-attack/panel-game#202 This would be BIG, mostly because it would accelerate player growth much more than the other suggestions

It should be worth mentioning that most of these 1p modes would also deserve their own mini tutorial for players entering them for the first time.

## Let them have achievements

Panel is a hard game. Beating a harder puzzle set for the first time, beating challenge mode on a certain level for the first time or with a certain continue-count, getting your first insert-catch...Panel should positively reinforce the player upon achieving something cool.

- [ ] panel-attack/panel-game#203 A no-brainer pretty much. Some of these are harder than others and we should start with the easy ones
- [ ] panel-attack/panel-game#189 In a similar vein, more funky stuff to look at
- [ ] panel-attack/panel-game#157 Indirect contributor but making it easier to find that one game where you played out of your mind would be pretty good
- [x] panel-attack/panel-game#357 Being able to work on puzzles as a visible progression would be a contributor to feeling achievement as even after a while of not playing puzzle mode, you will know whether you solved a puzzle for the first time or not
- [ ] No issue yet, but in general there should be something similar to the Pokemon Center in PPL, showing a comprehensive list of things the player achieved in the (singleplayer portion) game.
