### ISSUE TITLE
Full touch compatibility

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#427]
Tracking issue for things to make the client fully interactable via touch only.

- [ ]  panel-attack/panel-game#675  Add options for selecting touch as an input method inside of the input configuration
- [x] panel-attack/panel-game#488 ; the technical requirement to render stacks at different sizes
- [ ] Add a portrait / landscape toggle in the options and keep the game from autorotating.
This makes the game's canvas size dynamic and may need various forms of handling.
May want to take some inspiration from https://github.com/panel-attack/panel-attack/tree/portrait-mode although it might be wise to check out singular commits as the diff to current beta is unreadable.
This may also need a new auto updater to properly lock orientation.
- [x] Add a function for rendering matches in portrait mode, favorable for touch inputs on mobile devices that uses a bigger Stack.gfxScale for the player stack.
- [ ] panel-attack/panel-game#404
- [x] panel-attack/panel-game#131
- [ ] Add visual highlighting around selected grid element when using touch controls in select screen
- [x] implement swipe controls for menus
